### ISSUE TITLE
Wondering..

### ISSUE THREAD

**Issue by jkaberg** [Tuxity/angular-vlc#9]
Hey @Tuxity 

Nicely looking plugin, and I'm keen on using it.. Just one showstopper (for me); AngularJS

Is there a way to make it work without Angular? Seems like much for nothing when I only need this to get my VLC player to display nicely :-)

Whats the minimum code-wise requirements for it to work? Mind giving an example for me to start with? :-)

**Comment by mpgn** [comment]
@jkaberg check this link https://wiki.videolan.org/Documentation:WebPlugin/

**Comment by jkaberg** [comment]
Yeah I've been struggeling with it for several days now, problem is my menu gets hidden due to the vlc plugin haveing z index -1 @mpgn

**Comment by mpgn** [comment]
`windowless=true` is essential for a custom player.
You can create your own fullscreen like we did.

**Comment by legator** [comment]
Can you show me example of using angular-vlc? I am new in angular, so I have problem

**Comment by mpgn** [comment]
@legator  https://github.com/Tuxity/angular-vlc/blob/master/README.md#getting-started

**Comment by legator** [comment]
Yes, i made all step but I cannot run video

**Comment by mpgn** [comment]
@legator https://gist.github.com/mpgn/4229a08ffdc69e7a4e28
